# Generated by Django 2.1.4 on 2019-01-29 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='type',
        ),
    ]
