# Generated by Django 2.1.4 on 2019-02-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0001_initial'),
        ('client', '0008_client_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='raison_consultation',
            field=models.ManyToManyField(to='clientele.Probleme'),
        ),
    ]
