# Generated by Django 2.1.4 on 2019-02-04 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0001_initial'),
        ('client', '0010_client_famille_de_probleme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='famille_de_probleme',
        ),
        migrations.AddField(
            model_name='client',
            name='famille_de_probleme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientele.CategorieProbleme'),
        ),
        migrations.RemoveField(
            model_name='client',
            name='raison_consultation',
        ),
        migrations.AddField(
            model_name='client',
            name='raison_consultation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientele.Probleme'),
        ),
    ]
