# Generated by Django 2.1.4 on 2019-02-04 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_auto_20190204_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='famille_de_probleme',
            new_name='categorie_probleme',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='raison_consultation',
            new_name='probleme',
        ),
    ]
