# Generated by Django 2.1.4 on 2019-02-04 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_auto_20190204_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='date_de_naissance',
        ),
    ]
