# Generated by Django 2.1.4 on 2019-02-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_remove_client_date_de_naissance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='categorie_probleme',
        ),
        migrations.RemoveField(
            model_name='client',
            name='code_postale',
        ),
        migrations.RemoveField(
            model_name='client',
            name='probleme',
        ),
        migrations.RemoveField(
            model_name='client',
            name='rue',
        ),
        migrations.RemoveField(
            model_name='client',
            name='ville',
        ),
    ]
