# Generated by Django 2.1.4 on 2019-02-05 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_auto_20190205_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='adress',
        ),
        migrations.AlterField(
            model_name='client',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientele.CategorieClientele'),
        ),
    ]
