# Generated by Django 2.1.4 on 2019-02-05 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_auto_20190205_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['nom_fr']},
        ),
    ]
