# Generated by Django 2.1.4 on 2019-02-12 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_auto_20190205_1457'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
