# Generated by Django 2.1.4 on 2019-02-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_delete_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created_on',
            field=models.DateField(),
        ),
    ]
