# Generated by Django 2.1.4 on 2019-02-15 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0019_auto_20190215_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.Status'),
        ),
    ]
