# Generated by Django 2.1.4 on 2019-01-27 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fr', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['nom_fr'],
            },
        ),
        migrations.CreateModel(
            name='Mandat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fr', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['nom_fr'],
            },
        ),
        migrations.CreateModel(
            name='Orientation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('desc_fr', models.TextField(blank=True, max_length=1000)),
                ('desc_ang', models.TextField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Orientations',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Psychologue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permis_num', models.IntegerField(blank=True)),
                ('permis_date', models.DateField(blank=True, default='2018-01-01')),
                ('avatar', models.ImageField(upload_to='psy_avatar/')),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('fax', models.CharField(blank=True, max_length=10)),
                ('bio', models.TextField(blank=True, max_length=1700)),
                ('education', models.CharField(blank=True, max_length=70)),
                ('site_web', models.URLField(blank=True)),
                ('linked_in', models.URLField(blank=True)),
                ('langue', models.ManyToManyField(to='psychologues.Langue')),
                ('mandat', models.ManyToManyField(blank=True, to='psychologues.Mandat')),
                ('orientation', models.ManyToManyField(to='psychologues.Orientation')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='SecteurDePratique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fr', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['nom_fr'],
            },
        ),
        migrations.AddField(
            model_name='psychologue',
            name='secteur_de_pratique',
            field=models.ManyToManyField(to='psychologues.SecteurDePratique'),
        ),
        migrations.AddField(
            model_name='psychologue',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
