# Generated by Django 2.1.4 on 2019-01-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fr', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['nom_fr'],
            },
        ),
    ]
