# Generated by Django 2.1.4 on 2019-01-27 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0001_initial'),
        ('psychologues', '0002_intervention'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientele.Clientele')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychologues.Intervention')),
                ('orientation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychologues.Orientation')),
                ('psychologue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychologues.Psychologue')),
            ],
        ),
    ]
