# Generated by Django 2.1.4 on 2019-01-27 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psychologues', '0004_auto_20190127_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='orientation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='psychologues.Orientation'),
        ),
    ]
