# Generated by Django 2.1.4 on 2019-01-27 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychologues', '0005_auto_20190127_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence',
            name='clientele',
        ),
    ]
