# Generated by Django 2.1.4 on 2019-01-27 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0001_initial'),
        ('psychologues', '0007_auto_20190127_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOffert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientele.Clientele')),
            ],
        ),
        migrations.AlterModelOptions(
            name='competence',
            options={'ordering': ['psychologue', 'intervention', 'orientation']},
        ),
        migrations.AddField(
            model_name='serviceoffert',
            name='competence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychologues.Competence'),
        ),
    ]
