# Generated by Django 2.1.4 on 2019-02-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientele', '0001_initial'),
        ('psychologues', '0008_auto_20190127_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologue',
            name='clientele',
            field=models.ManyToManyField(blank=True, to='clientele.CategorieClientele'),
        ),
    ]
