# Generated by Django 2.1.4 on 2019-02-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20190205_1500'),
    ]

    operations = [
        #migrations.RemoveField(
         #   model_name='appointment',
          #  name='scheduled_on',
        #),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
