# Generated by Django 2.1.4 on 2019-02-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_auto_20190206_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.AddField(
            model_name='appointment',
            name='scheduled_on',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
