# Generated by Django 2.1.4 on 2019-01-27 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieClientele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fr', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['nom_fr'],
            },
        ),
        migrations.CreateModel(
            name='CategorieProbleme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fr', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['nom_fr'],
            },
        ),
        migrations.CreateModel(
            name='Clientele',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_clientele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientele.CategorieClientele')),
            ],
            options={
                'ordering': ['categorie_clientele', 'probleme'],
            },
        ),
        migrations.CreateModel(
            name='Probleme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fr', models.CharField(max_length=200)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientele.CategorieProbleme')),
            ],
            options={
                'ordering': ['categorie', 'nom_fr'],
            },
        ),
        migrations.AddField(
            model_name='clientele',
            name='probleme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientele.Probleme'),
        ),
        migrations.AlterUniqueTogether(
            name='probleme',
            unique_together={('categorie', 'nom_fr')},
        ),
        migrations.AlterUniqueTogether(
            name='clientele',
            unique_together={('categorie_clientele', 'probleme')},
        ),
    ]
