# Generated by Django 2.1.4 on 2019-02-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20190206_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='note',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
