# Generated by Django 2.1.4 on 2019-02-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20190208_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_on',
            field=models.DateField(),
        ),
    ]
