# Generated by Django 2.1.4 on 2019-01-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SectionText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fr', models.CharField(max_length=200, unique=True)),
                ('nom_en', models.CharField(blank=True, max_length=200)),
                ('text_fr', models.TextField(blank=True, max_length=1000)),
                ('text_an', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
